package form

import (
	"github.com/lambda-platform/lambda/DB"
	"github.com/lambda-platform/lambda/dataform"
	"github.com/lambda-platform/lambda/models"
	"github.com/thedevsaddam/govalidator"
	"lambda/lambda/models/form/formModels"
	"time"
)

var _ = time.Time{}
var _ = DB.Date{}

func JuramGeologyGaubm133Dataform() dataform.Dataform {
	return dataform.Dataform{
		Name:     "Биологийн гаралтай АҮБ",
		Identity: "id",
		Table:    "juram_geology_gaubm",
		Model:    new(formModels.JuramGeologyGaubm133),
		FieldTypes: map[string]string{
			"id":                                    "Text",
			"yronhii_medeelel":                      "Text",
			"heregjuulsen_arga":                     "Text",
			"zardal":                                "Text",
			"hohirol":                               "Text",
			"toim":                                  "Text",
			"shalguur_uzuulelt":                     "Text",
			"bio_disaster_type_id":                  "Select",
			"ovchin_ner_code":                       "Text",
			"aimagid":                               "Select",
			"sumid":                                 "Select",
			"bagid":                                 "Select",
			"gudamj":                                "Text",
			"baishin":                               "Text",
			"haashaa":                               "Text",
			"bairshil":                              "Geographic",
			"urtrag_neg":                            "Text",
			"orgorog_hoyor":                         "Text",
			"gurvanug_hayag":                        "Text",
			"m_o_ovog":                              "Text",
			"m_o_ner":                               "Text",
			"m_o_utas":                              "Number",
			"m_o_huis":                              "Radio",
			"source_bio_id":                         "Select",
			"info_souce_id":                         "Select",
			"m_o_tovch_utga":                        "Textarea",
			"hu_huleenavsan_ognoo":                  "DateTime",
			"ba_huleen_avsan_operator":              "Text",
			"angi_id":                               "Select",
			"salbar_id":                             "Select",
			"tsols_id":                              "Select",
			"ba_ovog":                               "Text",
			"ba_ner":                                "Text",
			"ba_garin_useg":                         "File",
			"shaltgaan_reason_id":                   "Select",
			"shaltgaan_ded_reason_id":               "Select",
			"test_id":                               "Select",
			"nb_file":                               "File",
			"nb_code":                               "Text",
			"chandralsan_bairshil":                  "Geographic",
			"urtrag_h":                              "Text",
			"orgorog_h":                             "Text",
			"ustgaliin_bairshil":                    "Geographic",
			"urtrag":                                "Text",
			"orgorog":                               "Text",
			"bat_baiguullaga_id":                    "Text",
			"bat_angi_id":                           "Select",
			"bat_salbar_id":                         "Select",
			"alban_tushaal_id":                      "Select",
			"tsol_id":                               "Select",
			"batal_alban_tushaal_id":                "Select",
			"batalgaajuulalt_alban_tushaal_id":      "Select",
			"gamshig_bolson_eseh":                   "Checkbox",
			"haldvart_ovchin_eseh":                  "Checkbox",
			"tav_deesh_eseh":                        "Checkbox",
			"nervegdesen_hun_eseh":                  "Checkbox",
			"hoyor_ba_deesh_eseh":                   "Checkbox",
			"nas_barsan_hun":                        "Number",
			"nutag_devsger_eseh":                    "Checkbox",
			"hamarsan_nurgiin_hemjee":               "Number",
			"uchirsan_bodit_hohirol_eseh":           "Checkbox",
			"tosovt_ezeleh_huvi":                    "Number",
			"measure_id":                            "Select",
			"ovchin_garsan_eseh":                    "Checkbox",
			"mal_ovchilson_eseh":                    "Checkbox",
			"mal_ovchilson_maliin_too":              "Number",
			"ustagsan_mal_arav_eseh":                "Number",
			"hamrah_huree":                          "Number",
			"mal_uchirsan_hohirol_hoyor_eseh":       "Checkbox",
			"mail_ezleh_huvi":                       "Number",
			"batalga_alban_tushaal_id":              "Text",
			"ovog_ner":                              "Text",
			"gariin_useg":                           "File",
			"ognoo":                                 "Date",
			"form_id":                               "Select",
			"created_at":                            "Text",
			"updated_at":                            "Text",
			"deleted_at":                            "Text",
			"hamrah_huree_hoyor_deesh_eseh":         "Checkbox",
			"shinj_ilersen_ognoo":                   "DateTime",
			"onchingarsan_ognoo":                    "DateTime",
			"hyzgaarlah_deglem_togtooson_ognoo":     "DateTime",
			"hyzgaarlah_deglem_tsutsalsan_ognoo":    "DateTime",
			"horio_togtooson_ognoo":                 "DateTime",
			"horio_tsutsalsan_ognoo":                "DateTime",
			"horogdson_mal_arav_deesh_eseh":         "Checkbox",
			"nervegdsen_hun_too":                    "Number",
			"nh_hemjih_negj_id":                     "Select",
			"nas_barsan_hun_hemjih_negj_id":         "Select",
			"h_nutag_hemjee_too":                    "Number",
			"h_nutag_hemjih_negj_id":                "Select",
			"ovchilson_mal_hemjih_negj_id":          "Select",
			"homroglon_ustagsan_mal_hemjih_negj_id": "Select",
			"hamrah_huree_hemjih_negj_id":           "Select",
			"uchirsan_bodit_hohirol_hemjih_negj_id": "Select",
			"sub_juram_geo_nervegdsen_hun_am":       "SubForm",
			"sub_juram_geo_nervegdsen_amitan":       "SubForm",
			"sub_juram_geo_avrah_sergeeh":           "SubForm",
			"bat_gariin_useg":                       "File",
			"bat_ovog":                              "Text",
			"bat_ner":                               "Text",
			"sub_juram_geo_uchirsan_bodit_horhirol": "SubForm",
			"batal_angi_id":                         "Select",
			"batal_salbar_id":                       "Select",
			"batal_tsol_id":                         "Select",
			"batal_ovog":                            "Text",
			"batal_ner":                             "Text",
			"batal_gar_useg":                        "File",
			"batalgaajuulalt_ovog":                  "Text",
			"batalgaajuulalt_ner":                   "Text",
			"batalgaajuulalt_gar_useg":              "File",
			"batalgaajuulalt_ognoo":                 "Date",
			"sub_juram_geo_gamshigt_ortson_hun_medeelel": "SubForm",
			"sub_juram_geo_horogdson_mal":                "SubForm",
			"sub_juram_geo_tejeever_amitan":              "SubForm",
			"sub_juram_geo_evdersen_ed_zuils":            "SubForm",
		},
		Formulas:           []models.Formula{},
		ValidationRules:    govalidator.MapData{},
		ValidationMessages: govalidator.MapData{},
		SubForms: []map[string]interface{}{
			map[string]interface{}{
				"connection_field": "juram_geo_id",
				"tableTypeColumn":  "",
				"tableTypeValue":   "",
				"table":            "sub_juram_geo_nervegdsen_hun_am",
				"parentIdentity":   "id",
				"subIdentity":      "id",
				"subForm":          SubJuramGeoNervegdsenHunAm147Dataform(),
				"subFormArray":     new([]formModels.SubJuramGeoNervegdsenHunAm147),
			},
			map[string]interface{}{
				"connection_field": "juram_geo_id",
				"tableTypeColumn":  "",
				"tableTypeValue":   "",
				"table":            "sub_juram_geo_nervegdsen_amitan",
				"parentIdentity":   "id",
				"subIdentity":      "id",
				"subForm":          SubJuramGeoNervegdsenAmitan148Dataform(),
				"subFormArray":     new([]formModels.SubJuramGeoNervegdsenAmitan148),
			},
			map[string]interface{}{
				"connection_field": "juram_geo_id",
				"tableTypeColumn":  "",
				"tableTypeValue":   "",
				"table":            "sub_juram_geo_avrah_sergeeh",
				"parentIdentity":   "id",
				"subIdentity":      "id",
				"subForm":          SubJuramGeoAvrahSergeeh149Dataform(),
				"subFormArray":     new([]formModels.SubJuramGeoAvrahSergeeh149),
			},
			map[string]interface{}{
				"connection_field": "juram_geo_id",
				"tableTypeColumn":  "",
				"tableTypeValue":   "",
				"table":            "sub_juram_geo_uchirsan_bodit_horhirol",
				"parentIdentity":   "id",
				"subIdentity":      "id",
				"subForm":          SubJuramGeoUchirsanBoditHorhirol150Dataform(),
				"subFormArray":     new([]formModels.SubJuramGeoUchirsanBoditHorhirol150),
			},
			map[string]interface{}{
				"connection_field": "juram_geo_id",
				"tableTypeColumn":  "",
				"tableTypeValue":   "",
				"table":            "sub_juram_geo_gamshigt_ortson_hun_medeelel",
				"parentIdentity":   "id",
				"subIdentity":      "id",
				"subForm":          SubJuramGeoGamshigtOrtsonHunMedeelel219Dataform(),
				"subFormArray":     new([]formModels.SubJuramGeoGamshigtOrtsonHunMedeelel219),
			},
			map[string]interface{}{
				"connection_field": "juram_goe_id",
				"tableTypeColumn":  "",
				"tableTypeValue":   "",
				"table":            "sub_juram_geo_horogdson_mal",
				"parentIdentity":   "id",
				"subIdentity":      "id",
				"subForm":          SubJuramGeoHorogdsonMal153Dataform(),
				"subFormArray":     new([]formModels.SubJuramGeoHorogdsonMal153),
			},
			map[string]interface{}{
				"connection_field": "juram_geo_id",
				"tableTypeColumn":  "",
				"tableTypeValue":   "",
				"table":            "sub_juram_geo_tejeever_amitan",
				"parentIdentity":   "id",
				"subIdentity":      "id",
				"subForm":          SubJuramGeoTejeeverAmitan154Dataform(),
				"subFormArray":     new([]formModels.SubJuramGeoTejeeverAmitan154),
			},
			map[string]interface{}{
				"connection_field": "juram_geo_id",
				"tableTypeColumn":  "",
				"tableTypeValue":   "",
				"table":            "sub_juram_geo_evdersen_ed_zuils",
				"parentIdentity":   "id",
				"subIdentity":      "id",
				"subForm":          SubJuramGeoEvdersenEdZuils155Dataform(),
				"subFormArray":     new([]formModels.SubJuramGeoEvdersenEdZuils155),
			}},
		AfterInsert:      nil,
		AfterUpdate:      nil,
		BeforeInsert:     nil,
		BeforeUpdate:     nil,
		TriggerNameSpace: "",
	}
}
